### ISSUE TITLE
Is my instance really up to date ?

### ISSUE THREAD

**Issue by stemy2** [YunoHost-Apps/pixelfed_ynh#117]
Hello,

Both my instance and pixelfed.social are up to date at the same version, but the second one seems to have more functionalities than the first. Why are they not exactly the same ?

**Comment by yalh76** [comment]
Without more explicit information no help can be provided. What you do is like going to the doctor and just saying `I'm sick`

So maybe they are not at the same version or maybe some functionalities has to be configured/activated. You should find more informations at https://docs.pixelfed.org/

**Comment by stemy2** [comment]
Actually, both instances are at the same version (0.10.9) but have some differences like these examples her below (left= my instance, right=other instance).

![Screenshot_20200615_132507](https://user-images.githubusercontent.com/22192600/84652932-fcd40880-aefb-11ea-93ca-de7f2bdef901.png)

![Screenshot_20200615_132534](https://user-images.githubusercontent.com/22192600/84652972-0a898e00-aefc-11ea-80f6-bacffcf01370.png)

![Screenshot_20200615_132608](https://user-images.githubusercontent.com/22192600/84652986-0f4e4200-aefc-11ea-996f-2d531332c8a1.png)

![Screenshot_20200615_132946](https://user-images.githubusercontent.com/22192600/84652993-12e1c900-aefc-11ea-822e-a7736a451055.png)

Theorically, they shouldn't exist because both instance are in the same version (i checked).

**Comment by lapineige** [comment]
Pixelfed flagship instance (pixelfed.social) is not using the same version as Yunohost one, most of the time.
It's because we only use version released (https://github.com/pixelfed/pixelfed/releases/) pixelfed.social seems to use latest master or another branch, but not the last release.
That means after a release is out, some features are added before the next one, and (at least of part of them) are added in pixelfed.social. Often the time between the release of a new version can be quite long, while new features are available in the master and advertised on social networks for instance.
You could sort of consider that pixelfed.social is somewhat running a kind of 0.10.10 beta version.

We can't really do anything about it. That's how pixelfed development works. The only way would be to always download the latest master, which would add quite a lot of work for us to setup, and might lead to some issues and bugs.
Sadly that means we can only wait for a new release (then usually in the coming week @yalh76 or me merge it into Yunohost repository).
I suppose there could we a way to do it manually via `composer update` command and so on, but I can't tell how to do it and if it would work well.
