### ISSUE TITLE
Compose UI doesn't work

### ISSUE THREAD

**Issue by lapineige** [YunoHost-Apps/pixelfed_ynh#67]
The compose UI popup doesn't work (it was also the case with 0.9.0).
The classical one works, but the other one let me upload the image, and after the 100% I have a pop-up "Oops, something went wrong".

I don't know if it's Yunohost or Pixelfed related.

**Comment by yalh76** [comment]
Have you tryed from another browser ? or on another pixelfed instance ?

I just tested the compose ui and was able to upload a photo and post.
Tested from:
* Chrome 74.0.3729.169 (Build officiel) (64 bits) / Windows 10 1803 64bits
* Firefox Quantum 67.0 (64 bits) / Windows 10 1803 64bits

**Comment by lapineige** [comment]
I've tested with Firefox 67 (linux), with extension.
And Tor Browser (linux too), without any extension. On this one it stays at 100% for a long time, then the same issue.

**Comment by yalh76** [comment]
Can you provide your instance url and allow me to create an account to test from my computer ?
or send the informations in a private message on mastodon ?

**Comment by raphgilles** [comment]
I have this issue too on my Windows 10 + Firefox or Chrome

But it's working great with MacOS + Firefox or Chrome or Safari

**Comment by yalh76** [comment]
Ok then, nothing consistent to help us understand what is the issue

**Comment by lapineige** [comment]
At least it doesn't seem to be a browser issue, or extension related.
Also tested with Firefox Nightly 69.

**Comment by StopTrackingUs** [comment]
I know the problem.  You need to make a couple of updates.  It will be required for all instance on yunohost (I Believe).  Fix by doing the following:

'sudo find / -name php.in'
'sudo nano /etc/php/7.2/fpm/php.ini' #update the file to be larger than 2 for max upload
'sudo nano /etc/php/7.0/fpm/php.ini' #update the file to be larger than 2 for max upload
'sudo systemctl restart php7.0-fpm'
'sudo systemctl restart php7.2-fpm'

Should be all good after that.  The problem is that fpm has its own upload limit that is set.  I can't figure out why this affects Pixelfed and not Peertube (probably because Peertube does no use fpm?) but once you update the max vars it will work perfectly.

**Comment by yalh76** [comment]
instead of changing global php configuration, I propose to only change pixelfed php configuration.

Can you test it and let me know if it's OK ?

You can upgrade using : `yunohost app upgrade pixelfed -u https://github.com/YunoHost-Apps/pixelfed_ynh/tree/testing`

**Comment by raspoutnik** [comment]
I had the same issue, the upgrade solved it on my instance.
Thanks !

**Comment by lapineige** [comment]
It worked :tada:

**Comment by lapineige** [comment]
So it seems that the new compose UI is using php limit, while the classic compose UI use nginx upload limit.
That's good to know 🤔

**Comment by StopTrackingUs** [comment]
Yeah I noticed that on some uploads the new one used php-fpm and on others php.ini from the server.  I couldn't tell until yesterday.  @dansup helped me fix it from the upstream.

![DeepinScreenshot_select-area_20190612143732](https://user-images.githubusercontent.com/50914501/59378491-68e8c300-8d22-11e9-9ebc-b50ac0d8c48c.png)
![DeepinScreenshot_select-area_20190612143755](https://user-images.githubusercontent.com/50914501/59378492-69815980-8d22-11e9-9af3-2ea0e6a8fcf9.png)
I just updated it on my server since our instance will be the only thing on our 2tb server.
